pipeline:
  build:
    image: openjdk:8-jdk
    commands:
      - chmod +x ./gradlew
      - ./gradlew clean build
  docker:
    image: plugins/docker:latest
    repo: parag3gwl/spring
    secrets: [ docker_username, docker_password ]
    debug: true
    tags: latest
  kube:
    image: vallard/drone-kube
    template: deployment.yaml
    namespace: mynamespace
    server: https://10.93.234.28:6433
