pipeline:
  build:
    image: openjdk:8-jdk
    commands:
      - chmod +x ./gradlew
      - ./gradlew clean build
  docker:
    image: plugins/docker:latest
    repo: parag3gwl/spring
    username: parag3gwl
    password: 1.Parag.Mangal
    debug: true
    tags: latest
    insecure: false
  kube:
    image: vallard/drone-kube
    template: deployment.yaml
    namespace: gke_api-project-561755557370_us-central1-a_api-cluster
    server: https://35.232.157.193
    token: MIIDDDCCAfSgAwIBAgIRAI5Hb0CWC6iTDGUqpmBthJUwDQYJKoZIhvcNAQELBQAw
LzEtMCsGA1UEAxMkNWJlM2U3NTgtMjFjOC00N2YyLTk0NWEtZDk5MjAwOTM0YThi
MB4XDTE4MTIyMDA2MDMzM1oXDTIzMTIxOTA3MDMzM1owLzEtMCsGA1UEAxMkNWJl
M2U3NTgtMjFjOC00N2YyLTk0NWEtZDk5MjAwOTM0YThiMIIBIjANBgkqhkiG9w0B
AQEFAAOCAQ8AMIIBCgKCAQEAs27gR7ZGvDCnj1BEkdRE6G0HOwui/f++QNTZeL+y
xgOeSEAl8Iy8OhP3Y+IJwUjQBF72cm/lkbJRsNJX0c78h9pRHCOHJUiWfMaePV4o
kuGxSA/XlV5vrf5QVCRbrVZ635ZumzY8kzXUad2CbZYquvUnsIpRjEb0gcGbGZ7N
fFpx+QPPiAVe2N9EMl+iQbekNozXoDRAV5uPOJkukwrZptiXo2PkdOyWddfj8e/N
hjYLVt+mjv6FWCuthLY4/mF9oC/abGKG61LEkCXKnNB5wu6gI0sftY4iXEQ4RcG8
i1exEb613SqBAv4KrroHwlvkryOkw6iwMSL3of+rKM4iwwIDAQABoyMwITAOBgNV
HQ8BAf8EBAMCAgQwDwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAQEA
liwv8phoSK4gUDHFY3MX2dtu4CNgPv8Wq2hr221Pzp05sqnh/GW7urYdZoqM2o3W
pVGUWFWJHnO4mZJGk+SzT00CLqbkrUWPLDRw49hsqo6nhPIwot02tFjzSlXqTzPY
r+KMV0s+T+c5F6fuQUx2ZAeVkP7T6DRADDoEaiGB6/O/c1zUjrfuI24d+rNmt4t2
SZ7pc3ISgX7DoEjq5cYbrxjo44vV/DE0XVNiSyTd5sHv4wpFPnKhjEtaMj5kTodM
vj4PLp9HG7qlwnFzKFFk7/so8gW7AAB8aLfWND5eI9jEi6avFl5UtWlIOHtpPXX/
3ZCUi5TskTYvVI/qiUrkAg==
