pipeline:
  deploy:
    image: quay.io/honestbee/drone-kubernetes
    kubernetes_server: https://35.232.157.193
    kubernetes_token: ya29.Glx4BjV6minxKhgbVNfad7i8KDgYYtQ7_7VkfWZt5mpcx_QlihVlMx9kyvpC3bf6u1tBM7FSp1qPl8Ep4QK-C2Ae0xXaRZdDGVTz6IO5paI-cSG7sirB_O7iBcib2Q
    deployment: my-deployment
    repo: parag3gwl/spring
    container: springbootapplication
    cluster: gke_api-project-561755557370_us-central1-a_api-cluster
    context: gke_api-project-561755557370_us-central1-a_api-cluster
    namespace: default
