pipeline:
  build:
    image: openjdk:8-jdk
    commands:
      - chmod +x ./gradlew
      - ./gradlew clean build
  docker:
    image: plugins/docker:latest
    repo: parag3gwl/spring
    username: parag3gwl
    password: 1.Parag.Mangal
    debug: true
    tags: latest
    insecure: false
  deploy:
    image: quay.io/honestbee/drone-kubernetes
    kubernetes_server: https://35.232.157.193
    kubernetes_token: Yq3AsF6Qb1ZC6CwI
    deployment: my-deployment
    repo: parag3gwl/spring
    container: springbootapplication
    tag: mytag
