apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spring-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: spring
    spec:
      containers:
      - name: spring
        image: spring:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080