apiVersion: v1
kind: Service
metadata:
  name: spring-service
  labels:
    name: spring-service
spec:
  type: NodePort
  ports:
    - port: 8088
      targetPort: 8088
      nodePort: 30030
  selector:
    app: spring-deployment
---

apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: spring-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring
  template:
    metadata:
      labels:
        app: spring
    spec:
      containers:
      - name: spring
        image: parag3gwl/spring:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
